name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Log in to Red Hat Registry
      run: echo "${{ secrets.REDHAT_PASSWORD }}" | docker login registry.redhat.io -u "${{ secrets.REDHAT_USERNAME }}" --password-stdin

    - name: Set tag variables
      id: vars
      run: echo "tag=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"

    - name: Build Docker image with timestamp tag
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          shu5hu/ansible-ee:${{ steps.vars.outputs.tag }}
          shu5hu/ansible-ee:latest
        secrets: |
          id=hub_token,env=AUTOMATION_HUB_TOKEN
