name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      REDHAT_USERNAME: ${{ vars.REDHAT_USERNAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to Red Hat Registry
        run: echo "${{ secrets.REDHAT_PASSWORD }}" | docker login registry.redhat.io -u "$REDHAT_USERNAME" --password-stdin

      - name: Set tag variables
        id: vars
        run: |
          echo "tag=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image (multi-stage)
        env:
          AUTOMATION_HUB_TOKEN: ${{ secrets.AUTOMATION_HUB_TOKEN }}
          REPO_NAME: ${{ vars.DOCKERHUB_REPO_NAME }}
          TAG: ${{ steps.vars.outputs.tag }}
        run: |
          docker build \
            --secret id=automation_hub_token,env=AUTOMATION_HUB_TOKEN \
            -t "$DOCKERHUB_USERNAME/$REPO_NAME:$TAG" \
            -t "$DOCKERHUB_USERNAME/$REPO_NAME:latest" \
            .

          docker push "$DOCKERHUB_USERNAME/$REPO_NAME:$TAG"
          docker push "$DOCKERHUB_USERNAME/$REPO_NAME:latest"
